/*  praxis: services for TSora IRC networks.
 *  include/config.h: Contains forward declarations for config.c.
 *
 *  Copyright (c) 2004 Eric Will <rakaur@malkier.net>
 *  Copyright (c) 2003-2004 shrike development team.
 *
 *  $Id$
 */

/* NOTE: This is *not* your standard config.h.  There are no settings in this
 * file for you to tweak.  This program uses output generated by autoconf
 * scripts for compile-time configuration.
 */

#ifndef INCLUDED_config_h
#define INCLUDED_config_h

#define PARAM_ERROR(ce)                                                       \
{                                                                             \
    ilog(L_INFO, "%s:%d: No parameter for configuration opion: %s",           \
         (ce)->ce_fileptr->cf_filename, (ce)->ce_varlinenum,                  \
         (ce)->ce_varname);                                                   \
                                                                              \
    return 1;                                                                 \
}

void configInit(void);
void configParse(void);
uchar configCheck(void);

#endif /* INCLUDED_config_h */
